# you can use conda env, to run it:
# conda env create -f environment.yml
# VSCode point to conda interpreter:
# shift + cmd + P
# Search Select Interpreter

name: adventofcode
dependencies:
  - numpy